// Icon names the prototype uses, mapped to Lucide components. Add names with `node scripts/add-icons.cjs <name>…`.
// Data stored in the database (e.g. search chips) refers to icons by these kebab-case names.
import {
  Activity,
  AlertCircle,
  AlignLeft,
  Archive,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  Bold,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  Captions,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleHelp,
  CircleMinus,
  CircleUserRound,
  CircleX,
  Clock,
  Cloud,
  Code,
  Compass,
  Copy,
  CornerDownRight,
  CreditCard,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileSearch,
  FileText,
  FileUp,
  Folder,
  FolderGit2,
  FolderOpen,
  Gauge,
  Globe,
  GraduationCap,
  HardDrive,
  Heading,
  Home,
  House,
  Image,
  Inbox,
  Info,
  Italic,
  KanbanSquare,
  Keyboard,
  Laptop,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListFilter,
  Loader,
  Lock,
  LogOut,
  Mail,
  Mailbox,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  MessageSquareReply,
  MessageSquareText,
  Mic,
  MicOff,
  Minus,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pause,
  PenLine,
  Pencil,
  PencilLine,
  PhoneOff,
  Pin,
  Play,
  Plug,
  Plus,
  Redo2,
  RefreshCw,
  Reply,
  RotateCcw,
  RotateCw,
  School,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Space,
  Sparkles,
  SquareKanban,
  Sun,
  Table,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Underline,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserRound,
  UserSearch,
  Video,
  VideoOff,
  Volume1,
  Volume2,
  Wallet,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "align-left": AlignLeft,
  archive: Archive,
  "arrow-down-right": ArrowDownRight,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  award: Award,
  "badge-check": BadgeCheck,
  "bar-chart-3": BarChart3,
  bell: Bell,
  bold: Bold,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  briefcase: Briefcase,
  bug: Bug,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  camera: Camera,
  captions: Captions,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-minus": CircleMinus,
  "circle-user-round": CircleUserRound,
  "circle-x": CircleX,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  copy: Copy,
  "corner-down-right": CornerDownRight,
  "credit-card": CreditCard,
  download: Download,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-check": FileCheck,
  "file-search": FileSearch,
  "file-text": FileText,
  "file-up": FileUp,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "folder-open": FolderOpen,
  gauge: Gauge,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hard-drive": HardDrive,
  heading: Heading,
  home: Home,
  house: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  italic: Italic,
  "kanban-square": KanbanSquare,
  keyboard: Keyboard,
  laptop: Laptop,
  "layout-grid": LayoutGrid,
  "layout-template": LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  "link-2": Link2,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  loader: Loader,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  mailbox: Mailbox,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  menu: Menu,
  "message-square": MessageSquare,
  "message-square-reply": MessageSquareReply,
  "message-square-text": MessageSquareText,
  mic: Mic,
  "mic-off": MicOff,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  paperclip: Paperclip,
  pause: Pause,
  "pen-line": PenLine,
  pencil: Pencil,
  "pencil-line": PencilLine,
  "phone-off": PhoneOff,
  pin: Pin,
  play: Play,
  plug: Plug,
  plus: Plus,
  "redo-2": Redo2,
  "refresh-cw": RefreshCw,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  school: School,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  "send-horizontal": SendHorizontal,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "skip-forward": SkipForward,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  space: Space,
  sparkles: Sparkles,
  "square-kanban": SquareKanban,
  sun: Sun,
  table: Table,
  tag: Tag,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  underline: Underline,
  "undo-2": Undo2,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  "user-round": UserRound,
  "user-search": UserSearch,
  video: Video,
  "video-off": VideoOff,
  "volume-1": Volume1,
  "volume-2": Volume2,
  wallet: Wallet,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
