/* Brand patch: swaps the placeholder dot Wordmark and footer logo for the supplied GetEmployed marks. */
(function(){const R=window.React;if(!R)return;const h=R.createElement;
function Wordmark({size=18,style}){return h("span",{style:{display:"inline-flex",alignItems:"center",gap:size*0.45,fontFamily:"var(--font-display)",fontWeight:600,fontSize:size,letterSpacing:-size*0.03,color:"var(--color-ink)",lineHeight:1,...style}},h("img",{src:"../assets/ge-mark.png",alt:"",width:Math.round(size*1.25),height:Math.round(size*1.25),style:{display:"block",objectFit:"contain"}}),"GetEmployed");}
function Footer({columns=[],note="© 2026 GetEmployed",githubUrl="https://github.com/ashmit27j/get-employed",onLink,style}){return h("footer",{style:{background:"var(--color-canvas)",borderTop:"1px solid var(--color-hairline)",padding:"64px 32px",fontSize:"var(--type-caption-size)",lineHeight:"var(--type-caption-lh)",color:"var(--color-ink-subtle)",...style}},
 h("div",{style:{maxWidth:"var(--container-max)",margin:"0 auto",display:"grid",gridTemplateColumns:"minmax(160px,1.4fr) repeat("+columns.length+",minmax(0,1fr))",gap:32},"data-r":"footer-grid"},
  h("div",{style:{display:"flex",flexDirection:"column",gap:14}},h("img",{src:"../assets/ge-wordmark.png",alt:"GetEmployed",style:{display:"block",height:44,width:"auto",alignSelf:"flex-start"}}),h("span",null,note),githubUrl&&h("a",{href:githubUrl,target:"_blank",rel:"noreferrer",style:{display:"inline-flex",alignItems:"center",gap:8,color:"var(--color-ink-subtle)",width:"fit-content"}},h("img",{src:"../assets/github.png",alt:"",width:16,height:16,style:{display:"block"}}),"Star on GitHub")),
  columns.map(c=>h("div",{key:c.title,style:{display:"flex",flexDirection:"column",gap:10}},h("span",{style:{color:"var(--color-ink)",fontWeight:500}},c.title),c.links.map(l=>h("a",{key:l,href:l==="GitHub"&&githubUrl?githubUrl:"#",onClick:onLink?e=>{if(!(l==="GitHub"&&githubUrl)){e.preventDefault();onLink(l);}}:undefined,style:{color:"var(--color-ink-subtle)"}},l))))));}
[window.GetEmployedDesignSystem_26a74c,window.GE_DS].forEach(ns=>{if(ns){try{ns.Wordmark=Wordmark;ns.Footer=Footer;}catch(e){}}});
})();
